trigger:
- main

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install Dependencies'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'Install Dependencies'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "No unit tests available"
      displayName: 'Run Dummy Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Function App'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription:'lab4connect'  # This is your Service Connection Name
        appType: functionApp
        appName: 'azure-func-hema8933095'                # Your Function App Name
        package: '$(System.DefaultWorkingDirectory)'
