trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: echo "Build step executed"
      displayName: 'Run Build Script'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Dummy Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "No unit tests available"
      displayName: 'Run Dummy Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Function App'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'lab4connect'  # Replace with your actual service connection name
        appType: 'functionApp'
        appName: 'azure-func-hema8933095'  # Replace with your actual Azure Function App name
        package: '$(System.DefaultWorkingDirectory)'
